docs: add GitHub Actions to CI/CD guide
loft-sh/loft pull request #151
Opened 2021-09-22 15:35 UTC by lizardruss

### Changes
- Add CI/CD examples for GitHub Actions

2021-09-22 15:40 UTC, FabianKramm commented
@LukasGentele please take a look

2021-09-24 17:15 UTC, LukasGentele requested changes

2021-09-24 17:15 UTC, LukasGentele commented on docs/pages/guides/ci-cd-pipelines.mdx
> +- [Delete Virtual Cluster](https://github.com/loft-sh/delete-vcluster): Deletes a Loft Virtual Cluster
We can remove `Loft` here. Space and Virtual Cluster are fine.

2021-09-24 17:15 UTC, LukasGentele commented on docs/pages/guides/ci-cd-pipelines.mdx
> +- [Delete Virtual Cluster](https://github.com/loft-sh/delete-vcluster): Deletes a Loft Virtual Cluster
same on the rest of the page tbh.

2021-09-24 17:15 UTC, LukasGentele commented on docs/pages/guides/ci-cd-pipelines.mdx
> +      - name: Create PR Space
Create Space for PR

2021-09-24 17:15 UTC, LukasGentele commented on docs/pages/guides/ci-cd-pipelines.mdx
> +### Using a Space for Pull Requests
Spaces for Pull Requests

2021-09-24 17:15 UTC, LukasGentele commented on docs/pages/guides/ci-cd-pipelines.mdx
> +#### Step by Step Explanation
No level-4 headlines here (also rest of the page)

2021-09-24 17:15 UTC, LukasGentele commented on docs/pages/guides/ci-cd-pipelines.mdx
> +#### Step by Step Explanation
Convert to regular text (see devspace docs: https://devspace.sh/cli/docs/configuration/images/image-tagging#image-image-repository)

2021-09-24 17:15 UTC, LukasGentele commented on docs/pages/guides/ci-cd-pipelines.mdx
> +### Using a Virtual Cluster for Pull Requests
Virtual Clusters for Pull Requests

2021-09-24 17:15 UTC, LukasGentele commented on docs/pages/guides/ci-cd-pipelines.mdx
> +## Using GitLab CI/CD Pipelines
\### GitLab CI/CD

2021-09-24 17:15 UTC, LukasGentele commented on docs/pages/guides/ci-cd-pipelines.mdx
> +## Using GitHub Actions
\## Integrations
\### GitHub Actions

=> Turn current h3 headlines into h4 headlines on the entire page.

2021-09-24 17:15 UTC, LukasGentele commented on docs/pages/guides/ci-cd-pipelines.mdx
>  ## Accessing Loft
Let's rename this to: Authentcation & Cluster Access

2021-09-24 17:15 UTC, LukasGentele commented on docs/pages/guides/ci-cd-pipelines.mdx
> +### Using Spaces for Merge Requests
-Using

2021-09-24 17:15 UTC, LukasGentele commented on docs/pages/guides/ci-cd-pipelines.mdx
> +### Using Virtual Clusters for Merge Requests
-Using

2021-09-24 18:37 UTC, LukasGentele approved these changes

2021-09-24 18:45 UTC, merged